/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package crygetter.gui;

import crygetter.model.AminoAcid;
import crygetter.model.AminoAcidDifference;
import crygetter.model.CryToxin;
import crygetter.utils.AlignmentColorScheme;
import crygetter.utils.Utils;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.data.ListOfArrayDataSource;
import net.sf.jasperreports.swing.JRViewer;
import org.biojava.bio.structure.Structure;
import org.biojava.bio.structure.align.gui.jmol.JmolPanel;
import org.biojava.bio.structure.io.PDBFileReader;

/**
 * Alignment analysis dialog.
 * 
 * @author David Buzatto
 */
public class AlignmentAnalysis extends javax.swing.JDialog {

    private DefaultListModel<CryToxin> proteinListModel1;
    private DefaultListModel<CryToxin> proteinListModel2;
    private DefaultListModel<AminoAcidDifference> aaDiffListModel;
    
    private CryToxin selectedCt1;
    private CryToxin selectedCt2;
    
    private JmolPanel jmolPanelAA1;
    private JmolPanel jmolPanelAA2;
    
    private List<CryToxin> ctList;
    private Map<String, List<String>> extractedData;
    private Map<String, AminoAcid> aaData;
    
    private AminoAcidDifference aaDiff;
    private AminoAcid aa1;
    private AminoAcid aa2;
    
    private int nonConserved;
    private int semiConservedMutation;
    private int conservedMutation;
    private int conserved;
    
    private int lenSeq1;
    private int lenSeq2;
    private String reportObs;
    
    private BufferedImage imgP1DomainsDiagram;
    private BufferedImage imgP2DomainsDiagram;
    private BufferedImage imgAlignmentDiagram;
    private List<Object[]> imagesAlignmentDiagram;
    
    /**
     * Creates new form AlignmentAnalysis
     */
    public AlignmentAnalysis( JDialog parent, boolean modal, List<CryToxin> ctList, Map<String, List<String>> extractedData, Map<String, AminoAcid> aaData ) {
        
        super( parent, modal );
        initComponents();
        
        this.ctList = ctList;
        this.extractedData = extractedData;
        this.aaData = aaData;
        
        proteinListModel1 = new DefaultListModel<>();
        proteinListModel2 = new DefaultListModel<>();
        aaDiffListModel = new DefaultListModel<>();
        
        listProteins1.setModel( proteinListModel1 );
        listProteins2.setModel( proteinListModel2 );
        listDiff.setModel( aaDiffListModel );
        
        listProteins1.setCellRenderer( new CryToxinListCellRenderer() );
        listProteins2.setCellRenderer( new CryToxinListCellRenderer() );
        
        jmolPanelAA1 = (JmolPanel) panelViewAA1;
        jmolPanelAA2 = (JmolPanel) panelViewAA2;
        
        loadProteinLists();
        updateUI();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProteins = new javax.swing.JPanel();
        panelProtein1 = new javax.swing.JPanel();
        scrollProteins1 = new javax.swing.JScrollPane();
        listProteins1 = new javax.swing.JList<CryToxin>();
        panelProtein2 = new javax.swing.JPanel();
        scrollProteins2 = new javax.swing.JScrollPane();
        listProteins2 = new javax.swing.JList<CryToxin>();
        btnAnalyse = new javax.swing.JButton();
        checkDoNotIncludeGaps = new javax.swing.JCheckBox();
        checkGenerateReport = new javax.swing.JCheckBox();
        lblColorScheme = new javax.swing.JLabel();
        comboColorScheme = new javax.swing.JComboBox();
        panelResults = new javax.swing.JPanel();
        panelDiff = new javax.swing.JPanel();
        spDiff = new javax.swing.JScrollPane();
        listDiff = new javax.swing.JList();
        lblPos = new javax.swing.JLabel();
        lblAA1 = new javax.swing.JLabel();
        lblAA2 = new javax.swing.JLabel();
        lblPosVal = new javax.swing.JLabel();
        lblAA1Val = new javax.swing.JLabel();
        lblAA2Val = new javax.swing.JLabel();
        panelContAA1 = new javax.swing.JPanel();
        panelViewAA1 = new JmolPanel();
        btnDetailsAA1 = new javax.swing.JButton();
        panelContAA2 = new javax.swing.JPanel();
        panelViewAA2 = new JmolPanel();
        btnDetailsAA2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Protein Analysis");
        setResizable(false);

        panelProteins.setBorder(javax.swing.BorderFactory.createTitledBorder("Proteins to Analyse"));

        panelProtein1.setBorder(javax.swing.BorderFactory.createTitledBorder("Protein 1"));

        listProteins1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listProteins1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listProteins1ValueChanged(evt);
            }
        });
        scrollProteins1.setViewportView(listProteins1);

        javax.swing.GroupLayout panelProtein1Layout = new javax.swing.GroupLayout(panelProtein1);
        panelProtein1.setLayout(panelProtein1Layout);
        panelProtein1Layout.setHorizontalGroup(
            panelProtein1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProtein1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollProteins1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelProtein1Layout.setVerticalGroup(
            panelProtein1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProtein1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollProteins1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelProtein2.setBorder(javax.swing.BorderFactory.createTitledBorder("Protein 2"));

        listProteins2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listProteins2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listProteins2ValueChanged(evt);
            }
        });
        scrollProteins2.setViewportView(listProteins2);

        javax.swing.GroupLayout panelProtein2Layout = new javax.swing.GroupLayout(panelProtein2);
        panelProtein2.setLayout(panelProtein2Layout);
        panelProtein2Layout.setHorizontalGroup(
            panelProtein2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProtein2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollProteins2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelProtein2Layout.setVerticalGroup(
            panelProtein2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProtein2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollProteins2)
                .addContainerGap())
        );

        btnAnalyse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crygetter/gui/icons/accept.png"))); // NOI18N
        btnAnalyse.setText("Analyse");
        btnAnalyse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyseActionPerformed(evt);
            }
        });

        checkDoNotIncludeGaps.setSelected(true);
        checkDoNotIncludeGaps.setText("Do not include gaps");

        checkGenerateReport.setText("Generate report");
        checkGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGenerateReportActionPerformed(evt);
            }
        });

        lblColorScheme.setText("Color Scheme:");

        comboColorScheme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ClustalX", "Zappo", "Taylor", "Hydrophobicity", "Helix Propensity", "Strand Propensity", "Turn Propensity", "Buried Index" }));
        comboColorScheme.setEnabled(false);

        javax.swing.GroupLayout panelProteinsLayout = new javax.swing.GroupLayout(panelProteins);
        panelProteins.setLayout(panelProteinsLayout);
        panelProteinsLayout.setHorizontalGroup(
            panelProteinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProteinsLayout.createSequentialGroup()
                .addGroup(panelProteinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProteinsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelProtein1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelProtein2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProteinsLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btnAnalyse))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProteinsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblColorScheme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProteinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkGenerateReport)
                            .addGroup(panelProteinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboColorScheme, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkDoNotIncludeGaps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProteinsLayout.setVerticalGroup(
            panelProteinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProteinsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProteinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelProtein1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProtein2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDoNotIncludeGaps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkGenerateReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProteinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColorScheme)
                    .addComponent(comboColorScheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnalyse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelResults.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));

        panelDiff.setBorder(javax.swing.BorderFactory.createTitledBorder("Differences"));

        listDiff.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        listDiff.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDiff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDiffMouseClicked(evt);
            }
        });
        listDiff.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listDiffValueChanged(evt);
            }
        });
        spDiff.setViewportView(listDiff);

        lblPos.setText("Position:");

        lblAA1.setText("AA 1:");

        lblAA2.setText("AA 2:");

        lblPosVal.setText(" ");

        lblAA1Val.setText(" ");

        lblAA2Val.setText(" ");

        javax.swing.GroupLayout panelDiffLayout = new javax.swing.GroupLayout(panelDiff);
        panelDiff.setLayout(panelDiffLayout);
        panelDiffLayout.setHorizontalGroup(
            panelDiffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDiffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spDiff, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelDiffLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(panelDiffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAA1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAA2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDiffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPosVal, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(lblAA1Val, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAA2Val, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDiffLayout.setVerticalGroup(
            panelDiffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spDiff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDiffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPos)
                    .addComponent(lblPosVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDiffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAA1)
                    .addComponent(lblAA1Val))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDiffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAA2)
                    .addComponent(lblAA2Val))
                .addGap(42, 42, 42))
        );

        panelContAA1.setBorder(javax.swing.BorderFactory.createTitledBorder("Protein 1 AA"));

        panelViewAA1.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout panelViewAA1Layout = new javax.swing.GroupLayout(panelViewAA1);
        panelViewAA1.setLayout(panelViewAA1Layout);
        panelViewAA1Layout.setHorizontalGroup(
            panelViewAA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelViewAA1Layout.setVerticalGroup(
            panelViewAA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        btnDetailsAA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crygetter/gui/icons/information.png"))); // NOI18N
        btnDetailsAA1.setText("Details");
        btnDetailsAA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsAA1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContAA1Layout = new javax.swing.GroupLayout(panelContAA1);
        panelContAA1.setLayout(panelContAA1Layout);
        panelContAA1Layout.setHorizontalGroup(
            panelContAA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContAA1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelViewAA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetailsAA1)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelContAA1Layout.setVerticalGroup(
            panelContAA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContAA1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContAA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDetailsAA1)
                    .addComponent(panelViewAA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContAA2.setBorder(javax.swing.BorderFactory.createTitledBorder("Protein 2 AA"));

        panelViewAA2.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout panelViewAA2Layout = new javax.swing.GroupLayout(panelViewAA2);
        panelViewAA2.setLayout(panelViewAA2Layout);
        panelViewAA2Layout.setHorizontalGroup(
            panelViewAA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelViewAA2Layout.setVerticalGroup(
            panelViewAA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        btnDetailsAA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crygetter/gui/icons/information.png"))); // NOI18N
        btnDetailsAA2.setText("Details");
        btnDetailsAA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsAA2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContAA2Layout = new javax.swing.GroupLayout(panelContAA2);
        panelContAA2.setLayout(panelContAA2Layout);
        panelContAA2Layout.setHorizontalGroup(
            panelContAA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContAA2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelViewAA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetailsAA2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContAA2Layout.setVerticalGroup(
            panelContAA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContAA2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContAA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDetailsAA2)
                    .addComponent(panelViewAA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelResultsLayout = new javax.swing.GroupLayout(panelResults);
        panelResults.setLayout(panelResultsLayout);
        panelResultsLayout.setHorizontalGroup(
            panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelContAA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContAA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResultsLayout.setVerticalGroup(
            panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDiff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultsLayout.createSequentialGroup()
                        .addComponent(panelContAA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelContAA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProteins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProteins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1076, 624));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listProteins1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listProteins1ValueChanged

        if ( listProteins1 != null ) {

            CryToxin selectedNow = (CryToxin) listProteins1.getSelectedValue();

            if ( selectedNow != null ) {
                selectedCt1 = selectedNow;
            }

        }

    }//GEN-LAST:event_listProteins1ValueChanged

    private void listProteins2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listProteins2ValueChanged
        
        if ( listProteins2 != null ) {

            CryToxin selectedNow = (CryToxin) listProteins2.getSelectedValue();

            if ( selectedNow != null ) {
                selectedCt2 = selectedNow;
            }

        }
        
    }//GEN-LAST:event_listProteins2ValueChanged

    private void btnAnalyseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyseActionPerformed
        
        if ( selectedCt1 != null && selectedCt2 != null && selectedCt1 != selectedCt2 ) {
            
            List<String> proteinData1 = extractedData.get( selectedCt1.name );
            List<String> proteinData2 = extractedData.get( selectedCt2.name );
            List<String> alnResult = extractedData.get( "aln" );
            List<AminoAcidDifference> aaDiffs = new ArrayList<>();
            
            nonConserved = 0;
            semiConservedMutation = 0;
            conservedMutation = 0;
            conserved = 0;
            
            lenSeq1 = 0;
            lenSeq2 = 0;
            
            for ( int i = 0; i < proteinData1.size(); i++ ) {
                
                char[] seq1 = proteinData1.get( i ).toCharArray();
                char[] seq2 = proteinData2.get( i ).toCharArray();
                char[] res = alnResult.get( i ).toCharArray();
                
                for ( int j = 0; j < seq1.length; j++ ) {
                    
                    if ( seq1[j] != '-' ) {
                        lenSeq1++;
                    }
                    
                    if ( seq2[j] != '-' ) {
                        lenSeq2++;
                    }
                    
                    switch ( res[j] ) {
                        case ' ':
                            nonConserved++;
                            break;
                        case '.':
                            semiConservedMutation++;
                            break;
                        case ':':
                            conservedMutation++;
                            break;
                        case '*':
                            conserved++;
                            break;
                            
                    }
                    
                    if ( checkDoNotIncludeGaps.isSelected() ) {
                        if ( seq1[j] != seq2[j] && seq1[j] != '-' && seq2[j] != '-' ) {
                            aaDiffs.add( new AminoAcidDifference( seq1[j], seq2[j], (i * 60) + j + 1, res[j] ) );
                        }
                    } else {
                        if ( seq1[j] != seq2[j] ) {
                            aaDiffs.add( new AminoAcidDifference( seq1[j], seq2[j], (i * 60) + j + 1, res[j] ) );
                        }
                    }
                    
                }
                
            }
            
            if ( checkGenerateReport.isSelected() ) {
                
                reportObs = JOptionPane.showInputDialog( "Report Observation:" );
                
                AlignmentColorScheme.ResultColorScheme colorScheme;
                
                switch ( comboColorScheme.getSelectedIndex() ) {
                    case 0:
                        colorScheme = AlignmentColorScheme.ResultColorScheme.CLUSTALX;
                        break;
                    case 1:
                        colorScheme = AlignmentColorScheme.ResultColorScheme.ZAPPO;
                        break;
                    case 2:
                        colorScheme = AlignmentColorScheme.ResultColorScheme.TAYLOR;
                        break;
                    case 3:
                        colorScheme = AlignmentColorScheme.ResultColorScheme.HYDROPHOBICITY;
                        break;
                    case 4:
                        colorScheme = AlignmentColorScheme.ResultColorScheme.HELYX_PROPENSITY;
                        break;
                    case 5:
                        colorScheme = AlignmentColorScheme.ResultColorScheme.STRAND_PROPENSITY;
                        break;
                    case 6:
                        colorScheme = AlignmentColorScheme.ResultColorScheme.TURN_PROPENSITY;
                        break;
                    case 7:
                        colorScheme = AlignmentColorScheme.ResultColorScheme.BURIED_INDEX;
                        break;
                    default:
                        colorScheme = AlignmentColorScheme.ResultColorScheme.CLUSTALX;
                        break;
                }
                
                imgAlignmentDiagram = Utils.generateAlignmentImage( selectedCt1.name, selectedCt2.name,
                        proteinData1, proteinData2, alnResult, colorScheme );
                
                imagesAlignmentDiagram = Utils.sliceImage( imgAlignmentDiagram, 82 );
                
                imgP1DomainsDiagram = Utils.generateProteinSchemeImage( selectedCt1, false );
                imgP2DomainsDiagram = Utils.generateProteinSchemeImage( selectedCt2, false );
                
                generateReport();
                
            }
            
            if ( !aaDiffs.isEmpty() ) {
                
                aaDiffListModel.clear();
                
                for ( AminoAcidDifference aad : aaDiffs ) {
                    aaDiffListModel.addElement( aad );
                }
                
            } else {
                JOptionPane.showMessageDialog( this, "There are no differences between the\n"
                        + "proteins \"" + selectedCt1.name + "\" and \"" + selectedCt2.name + "\"", 
                        "Information", JOptionPane.INFORMATION_MESSAGE );
            }
            
        } else {
            JOptionPane.showMessageDialog( this, "You must select two different proteins to analyse.",
                    "Warning", JOptionPane.WARNING_MESSAGE );
        }
        
        aaDiff = null;
        aa1 = null;
        aa2 = null;
        
        updateUI();
        
    }//GEN-LAST:event_btnAnalyseActionPerformed

    private void listDiffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDiffMouseClicked
        
        /*if ( listDiff.getSelectedValue() != null ) {
            
            aaDiff = (AminoAcidDifference) listDiff.getSelectedValue();
            aa1 = aaData.get( String.valueOf( aaDiff.aa1 ) );
            aa2 = aaData.get( String.valueOf( aaDiff.aa2 ) );
            
            updateUI();
            
        }*/
        
    }//GEN-LAST:event_listDiffMouseClicked

    private void btnDetailsAA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsAA1ActionPerformed
        
        if ( aa1 != null ) {
            AminoAcidDetails aad = new AminoAcidDetails( this, true, aa1 );
            aad.setVisible( true );
        }
        
    }//GEN-LAST:event_btnDetailsAA1ActionPerformed

    private void btnDetailsAA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsAA2ActionPerformed
        
        if ( aa2 != null ) {
            AminoAcidDetails aad = new AminoAcidDetails( this, true, aa2 );
            aad.setVisible( true );
        }
        
    }//GEN-LAST:event_btnDetailsAA2ActionPerformed

    private void listDiffValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDiffValueChanged
        
        if ( listDiff.getSelectedValue() != null ) {
            
            aaDiff = (AminoAcidDifference) listDiff.getSelectedValue();
            aa1 = aaData.get( String.valueOf( aaDiff.aa1 ) );
            aa2 = aaData.get( String.valueOf( aaDiff.aa2 ) );
            
            updateUI();
            
        }
        
    }//GEN-LAST:event_listDiffValueChanged

    private void checkGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGenerateReportActionPerformed
        
        if ( checkGenerateReport.isSelected() ) {
            comboColorScheme.setEnabled( true );
        } else {
            comboColorScheme.setEnabled( false );
        }
        
    }//GEN-LAST:event_checkGenerateReportActionPerformed

    private void generateReport() {
        
        Map<String, Object> params = new HashMap<>();
        
        params.put( "p1Name" , selectedCt1.name );
        params.put( "p1Acc" , selectedCt1.accessionNo );
        params.put( "p1ProtId" , selectedCt1.ncbiProtein );
        params.put( "p1NucId" , selectedCt1.ncbiNucleotide );
        params.put( "p1Len" , String.valueOf( selectedCt1.proteinSequence.length() ) );
        
        if ( selectedCt1.domains.size() == 3 ) {
            params.put( "p1D1Len" , String.valueOf( selectedCt1.domains.get( 0 ).interval.end - selectedCt1.domains.get( 0 ).interval.start + 1 ) );
            params.put( "p1D2Len" , String.valueOf( selectedCt1.domains.get( 1 ).interval.end - selectedCt1.domains.get( 1 ).interval.start + 1 ) );
            params.put( "p1D3Len" , String.valueOf( selectedCt1.domains.get( 2 ).interval.end - selectedCt1.domains.get( 2 ).interval.start + 1 ) );
        }
        
        params.put( "p2Name" , selectedCt2.name );
        params.put( "p2Acc" , selectedCt2.accessionNo );
        params.put( "p2ProtId" , selectedCt2.ncbiProtein );
        params.put( "p2NucId" , selectedCt2.ncbiNucleotide );
        params.put( "p2Len" , String.valueOf( selectedCt2.proteinSequence.length() ) );
        
        if ( selectedCt2.domains.size() == 3 ) {
            params.put( "p2D1Len" , String.valueOf( selectedCt2.domains.get( 0 ).interval.end - selectedCt2.domains.get( 0 ).interval.start + 1 ) );
            params.put( "p2D2Len" , String.valueOf( selectedCt2.domains.get( 1 ).interval.end - selectedCt2.domains.get( 1 ).interval.start + 1 ) );
            params.put( "p2D3Len" , String.valueOf( selectedCt2.domains.get( 2 ).interval.end - selectedCt2.domains.get( 2 ).interval.start + 1 ) );
        }
            
        params.put( "nonConserved", String.valueOf( nonConserved ) );
        params.put( "semiConservedMutation", String.valueOf( semiConservedMutation ) );
        params.put( "conservedMutation", String.valueOf( conservedMutation ) );
        params.put( "conserved", String.valueOf( conserved ) );
        params.put( "ccm", String.valueOf( conserved + conservedMutation ) );
        
        DecimalFormat df = new DecimalFormat( "#.##" );
        
        params.put( "p1NonConserved", df.format( (double) nonConserved / (double) lenSeq1 ) + "%" );
        params.put( "p1SemiConservedMutation", df.format( (double) semiConservedMutation / (double) lenSeq1 ) + "%" );
        params.put( "p1ConservedMutation", df.format( (double) conservedMutation / (double) lenSeq1 ) + "%" );
        params.put( "p1Conserved", df.format( (double) conserved / (double) lenSeq1 ) + "%" );
        params.put( "p1CCM", df.format( ( (double) conserved + (double) conservedMutation ) / (double) lenSeq1 ) + "%" );
        
        params.put( "p2NonConserved", df.format( (double) nonConserved / (double) lenSeq2 ) + "%" );
        params.put( "p2SemiConservedMutation", df.format( (double) semiConservedMutation / (double) lenSeq2 ) + "%" );
        params.put( "p2ConservedMutation", df.format( (double) conservedMutation / (double) lenSeq2 ) + "%" );
        params.put( "p2Conserved", df.format( (double) conserved / (double) lenSeq2 ) + "%" );
        params.put( "p2CCM", df.format( ( (double) conserved + (double) conservedMutation ) / (double) lenSeq2 ) + "%" );
        
        params.put( "obs", reportObs );
        
        params.put( "imgP1DomainsDiagram", imgP1DomainsDiagram );
        params.put( "imgP2DomainsDiagram", imgP2DomainsDiagram );
        
        JRDataSource dataSource = new ListOfArrayDataSource( imagesAlignmentDiagram, new String[]{ "imageSlice" } );

        try {
            
            final JasperPrint print = JasperFillManager.fillReport(
                    getClass().getResourceAsStream( "/proteinAnalysis.jasper" ),
                    params, dataSource );

            final JDialog thisFrame = this;
            
            SwingUtilities.invokeLater( new Runnable() {

                @Override
                public void run() {
                    
                    JRViewer viewer = new JRViewer( print );
                    JDialog reportFrame = new JDialog( thisFrame, "Cry Protein Analysis Results", true );
                    reportFrame.add( viewer, BorderLayout.CENTER );
                    reportFrame.setSize( 900, 700 );
                    reportFrame.setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE );
                    reportFrame.setLocationRelativeTo( null );
                    reportFrame.setVisible( true );
                    
                }
                
            });
        
        } catch ( JRException exc ) {
            Utils.showExceptionMessage( this, exc );
        }
        
    }
    
    private void loadProteinLists() {
        
        for ( Entry<String, List<String>> e : extractedData.entrySet() ) {
            
            if ( !e.getKey().equals( "aln" ) ) {
                
                for ( int i = 0; i < ctList.size(); i++ ) {
                    
                    CryToxin ct = ctList.get( i );
                    
                    if ( ct.name.equals( e.getKey() ) ) {
                        proteinListModel1.addElement( ct );
                        proteinListModel2.addElement( ct );
                    }
                    
                }
                
            }
            
        }
        
        listProteins1.updateUI();
        listProteins2.updateUI();
        
    }
    
    private void updateUI() {
        
        PDBFileReader pdbr = new PDBFileReader();
        
        try {
            
            if ( aaDiff == null ) {

                lblPosVal.setText( " " );
                lblAA1Val.setText( " " );
                lblAA2Val.setText( " " );

                jmolPanelAA1.setStructure( pdbr.getStructure( getClass().getResource( "/clean.pdb" ) ) );
                jmolPanelAA2.setStructure( pdbr.getStructure( getClass().getResource( "/clean.pdb" ) ) );
                jmolPanelAA1.getViewer().runScript( "zoom 1" );
                jmolPanelAA2.getViewer().runScript( "zoom 1" );

            } else {

                lblPosVal.setText( String.valueOf( aaDiff.position ) );
                lblAA1Val.setText( String.valueOf( aaDiff.aa1 ) );
                lblAA2Val.setText( String.valueOf( aaDiff.aa2 ) );

                Structure strucAA1;
                Structure strucAA2;

                if ( aa1 != null ) {
                    strucAA1 = pdbr.getStructure( getClass().getResource( aa1.pdbFile ) );
                } else {
                    strucAA1 = pdbr.getStructure( getClass().getResource( "/clean.pdb" ) );
                }
                jmolPanelAA1.setStructure( strucAA1 );
                
                if ( aa2 != null ) {
                    strucAA2 = pdbr.getStructure( getClass().getResource( aa2.pdbFile ) );
                } else {
                    strucAA2 = pdbr.getStructure( getClass().getResource( "/clean.pdb" ) );
                }
                jmolPanelAA2.setStructure( strucAA2 );
                
                if ( aa1 == null ) {
                    jmolPanelAA1.getViewer().runScript( "zoom 1" );
                }
                
                if ( aa2 == null ) {
                    jmolPanelAA2.getViewer().runScript( "zoom 1" );
                }
                
            }
            
        } catch ( IOException exc ) {
            Utils.showExceptionMessage( this, exc );
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyse;
    private javax.swing.JButton btnDetailsAA1;
    private javax.swing.JButton btnDetailsAA2;
    private javax.swing.JCheckBox checkDoNotIncludeGaps;
    private javax.swing.JCheckBox checkGenerateReport;
    private javax.swing.JComboBox comboColorScheme;
    private javax.swing.JLabel lblAA1;
    private javax.swing.JLabel lblAA1Val;
    private javax.swing.JLabel lblAA2;
    private javax.swing.JLabel lblAA2Val;
    private javax.swing.JLabel lblColorScheme;
    private javax.swing.JLabel lblPos;
    private javax.swing.JLabel lblPosVal;
    private javax.swing.JList listDiff;
    private javax.swing.JList<CryToxin> listProteins1;
    private javax.swing.JList<CryToxin> listProteins2;
    private javax.swing.JPanel panelContAA1;
    private javax.swing.JPanel panelContAA2;
    private javax.swing.JPanel panelDiff;
    private javax.swing.JPanel panelProtein1;
    private javax.swing.JPanel panelProtein2;
    private javax.swing.JPanel panelProteins;
    private javax.swing.JPanel panelResults;
    private javax.swing.JPanel panelViewAA1;
    private javax.swing.JPanel panelViewAA2;
    private javax.swing.JScrollPane scrollProteins1;
    private javax.swing.JScrollPane scrollProteins2;
    private javax.swing.JScrollPane spDiff;
    // End of variables declaration//GEN-END:variables
}
