/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package crygetter.gui;

import crygetter.model.AminoAcid;
import crygetter.utils.Utils;
import java.io.IOException;
import javax.swing.JDialog;
import org.biojava.bio.structure.Structure;
import org.biojava.bio.structure.align.gui.jmol.JmolPanel;
import org.biojava.bio.structure.io.PDBFileReader;

/**
 * Amino acid detail dialog.
 * 
 * @author David Buzatto
 */
public class AminoAcidDetails extends javax.swing.JDialog {

    /**
     * Creates new form AminoAcidDetails
     */
    public AminoAcidDetails( JDialog parent, boolean modal, AminoAcid aa ) {
        
        super( parent, modal );
        initComponents();
        
        lblNameVal.setText( aa.name );
        lbl3Val.setText( aa.threeLetter );
        lbl1Val.setText( aa.oneLetter );
        lblSCPVal.setText( aa.sideChainPolarity );
        lblSCCVal.setText( aa.sideChainCharge );
        lblHIVal.setText( aa.hydropathyIndex );
        
        try {
            
            PDBFileReader pdbr = new PDBFileReader();
            Structure struc = pdbr.getStructure( getClass().getResource( aa.pdbFile ) );
            ((JmolPanel) panel3DPaint).setStructure( struc );
            ((ImagePanel) panelSFPaint).setImage( getClass().getResourceAsStream( aa.pngFile ) );
            
        } catch ( IOException exc ) {
            Utils.showExceptionMessage( this, exc );
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetails = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblSCP = new javax.swing.JLabel();
        lblSCC = new javax.swing.JLabel();
        lblHI = new javax.swing.JLabel();
        lblNameVal = new javax.swing.JLabel();
        lbl3Val = new javax.swing.JLabel();
        lbl1Val = new javax.swing.JLabel();
        lblSCPVal = new javax.swing.JLabel();
        lblSCCVal = new javax.swing.JLabel();
        lblHIVal = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        panelSF = new javax.swing.JPanel();
        panelSFPaint = new ImagePanel();
        panel3D = new javax.swing.JPanel();
        panel3DPaint = new JmolPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Amino Acid Details");
        setResizable(false);

        panelDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        lblName.setText("Name:");

        lbl3.setText("3-Letter:");

        lbl1.setText("1-Letter:");

        lblSCP.setText("Side-chain polarity:");

        lblSCC.setText("Side-chain charge (pH 7.4):");

        lblHI.setText("Hydropathy index:");

        lblNameVal.setText(" ");

        lbl3Val.setText(" ");

        lbl1Val.setText(" ");

        lblSCPVal.setText(" ");

        lblSCCVal.setText(" ");

        lblHIVal.setText(" ");

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crygetter/gui/icons/accept.png"))); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetailsLayout = new javax.swing.GroupLayout(panelDetails);
        panelDetails.setLayout(panelDetailsLayout);
        panelDetailsLayout.setHorizontalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailsLayout.createSequentialGroup()
                        .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSCP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSCC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHI, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl3Val, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl1Val, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSCPVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSCCVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHIVal, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetailsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)))
                .addContainerGap())
        );
        panelDetailsLayout.setVerticalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblNameVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(lbl3Val))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lbl1Val))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSCP)
                    .addComponent(lblSCPVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSCC)
                    .addComponent(lblSCCVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHI)
                    .addComponent(lblHIVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
        );

        panelSF.setBorder(javax.swing.BorderFactory.createTitledBorder("Structural Formula"));

        javax.swing.GroupLayout panelSFPaintLayout = new javax.swing.GroupLayout(panelSFPaint);
        panelSFPaint.setLayout(panelSFPaintLayout);
        panelSFPaintLayout.setHorizontalGroup(
            panelSFPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        panelSFPaintLayout.setVerticalGroup(
            panelSFPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSFLayout = new javax.swing.GroupLayout(panelSF);
        panelSF.setLayout(panelSFLayout);
        panelSFLayout.setHorizontalGroup(
            panelSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSFPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSFLayout.setVerticalGroup(
            panelSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSFPaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel3D.setBorder(javax.swing.BorderFactory.createTitledBorder("3D Structure"));
        panel3D.setToolTipText("");

        panel3DPaint.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout panel3DPaintLayout = new javax.swing.GroupLayout(panel3DPaint);
        panel3DPaint.setLayout(panel3DPaintLayout);
        panel3DPaintLayout.setHorizontalGroup(
            panel3DPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panel3DPaintLayout.setVerticalGroup(
            panel3DPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel3DLayout = new javax.swing.GroupLayout(panel3D);
        panel3D.setLayout(panel3DLayout);
        panel3DLayout.setHorizontalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel3DPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3DLayout.setVerticalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel3DPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(952, 405));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl1Val;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl3Val;
    private javax.swing.JLabel lblHI;
    private javax.swing.JLabel lblHIVal;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameVal;
    private javax.swing.JLabel lblSCC;
    private javax.swing.JLabel lblSCCVal;
    private javax.swing.JLabel lblSCP;
    private javax.swing.JLabel lblSCPVal;
    private javax.swing.JPanel panel3D;
    private javax.swing.JPanel panel3DPaint;
    private javax.swing.JPanel panelDetails;
    private javax.swing.JPanel panelSF;
    private javax.swing.JPanel panelSFPaint;
    // End of variables declaration//GEN-END:variables
}
