/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package crygetter.gui;

import crygetter.model.AminoAcid;
import crygetter.utils.Utils;
import java.io.IOException;
import javax.swing.JDialog;
import org.biojava.bio.structure.Structure;
import org.biojava.bio.structure.align.gui.jmol.JmolPanel;
import org.biojava.bio.structure.io.PDBFileReader;

/**
 * Amino acid detail dialog.
 * 
 * @author David Buzatto
 */
public class AminoAcidDetails extends javax.swing.JDialog {

    /**
     * Creates new form AminoAcidDetails
     */
    public AminoAcidDetails( JDialog parent, boolean modal, AminoAcid aa ) {
        
        super( parent, modal );
        initComponents();
        
        lblNameV.setText( aa.name );
        lbl3V.setText( aa.threeLetter );
        lbl1V.setText( aa.oneLetter );
        lblGroupV.setText( aa.group );
        lblSCGV.setText( aa.sideChainGroup );
        lblSCPV.setText( aa.sideChainPolarity );
        lblSCCV.setText( aa.sideChainCharge );
        lblHIV.setText( aa.hydropathyIndex );
        lblMMV.setText( aa.molecularMass );
        lblVDWV.setText( aa.vanderWaalsVolume + " \u212b\u00b3" );
        lblFPV.setText( aa.frequencyInProteins + "%" );
        lblSAV.setText( aa.surfaceArea + " \u212b\u00b2" );
        
        for ( String obs : aa.observations ) {
            areaObs.append( "- " + obs + "\n" );
        }
        
        try {
            
            PDBFileReader pdbr = new PDBFileReader();
            Structure struc = pdbr.getStructure( getClass().getResource( aa.pdbFile ) );
            ((JmolPanel) panel3DPaint).setStructure( struc );
            ((ImagePanel) panelSFPaint).setImage( getClass().getResourceAsStream( aa.pngFile ) );
            
        } catch ( IOException exc ) {
            Utils.showExceptionMessage( this, exc );
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetails = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblGroup = new javax.swing.JLabel();
        lblSCG = new javax.swing.JLabel();
        lblSCP = new javax.swing.JLabel();
        lblSCC = new javax.swing.JLabel();
        lblHI = new javax.swing.JLabel();
        lblMM = new javax.swing.JLabel();
        lblVDW = new javax.swing.JLabel();
        lblFP = new javax.swing.JLabel();
        lblSA = new javax.swing.JLabel();
        lblObs = new javax.swing.JLabel();
        lblNameV = new javax.swing.JLabel();
        lbl3V = new javax.swing.JLabel();
        lbl1V = new javax.swing.JLabel();
        lblGroupV = new javax.swing.JLabel();
        lblSCGV = new javax.swing.JLabel();
        lblSCPV = new javax.swing.JLabel();
        lblSCCV = new javax.swing.JLabel();
        lblHIV = new javax.swing.JLabel();
        lblMMV = new javax.swing.JLabel();
        lblVDWV = new javax.swing.JLabel();
        lblFPV = new javax.swing.JLabel();
        lblSAV = new javax.swing.JLabel();
        spObs = new javax.swing.JScrollPane();
        areaObs = new javax.swing.JTextArea();
        panelSF = new javax.swing.JPanel();
        panelSFPaint = new ImagePanel();
        panel3D = new javax.swing.JPanel();
        panel3DPaint = new JmolPanel();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Amino Acid Details");
        setResizable(false);

        panelDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        lblName.setText("Name:");

        lbl3.setText("3-Letter:");

        lbl1.setText("1-Letter:");

        lblGroup.setText("Group:");

        lblSCG.setText("Side-chain Group:");

        lblSCP.setText("Side-chain Polarity:");

        lblSCC.setText("Side-chain Charge (pH 7.4):");

        lblHI.setText("Hydropathy Index:");

        lblMM.setText("Molecular Mass:");

        lblVDW.setText("Van der Waals Volume:");

        lblFP.setText("Frequency in Proteins:");

        lblSA.setText("Surface Area:");

        lblObs.setText("Observations:");

        lblNameV.setText(" ");

        lbl3V.setText(" ");

        lbl1V.setText(" ");

        lblGroupV.setText(" ");

        lblSCGV.setText(" ");

        lblSCPV.setText(" ");

        lblSCCV.setText(" ");

        lblHIV.setText(" ");

        lblMMV.setText(" ");

        lblVDWV.setText(" ");

        lblFPV.setText(" ");

        lblSAV.setText(" ");

        areaObs.setColumns(20);
        areaObs.setRows(5);
        spObs.setViewportView(areaObs);

        javax.swing.GroupLayout panelDetailsLayout = new javax.swing.GroupLayout(panelDetails);
        panelDetails.setLayout(panelDetailsLayout);
        panelDetailsLayout.setHorizontalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailsLayout.createSequentialGroup()
                        .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGroup, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSCG, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSCP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSCC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMM, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVDW, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSA, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl3V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl1V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGroupV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSCGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSCPV, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(lblSCCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMMV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVDWV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSAV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(spObs)
                    .addGroup(panelDetailsLayout.createSequentialGroup()
                        .addComponent(lblObs)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDetailsLayout.setVerticalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblNameV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(lbl3V))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lbl1V))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGroup)
                    .addComponent(lblGroupV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSCG)
                    .addComponent(lblSCGV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSCP)
                    .addComponent(lblSCPV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSCC)
                    .addComponent(lblSCCV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHI)
                    .addComponent(lblHIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMM)
                    .addComponent(lblMMV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVDW)
                    .addComponent(lblVDWV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFP)
                    .addComponent(lblFPV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSA)
                    .addComponent(lblSAV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spObs)
                .addContainerGap())
        );

        panelSF.setBorder(javax.swing.BorderFactory.createTitledBorder("Structural Formula"));

        panelSFPaint.setPreferredSize(new java.awt.Dimension(154, 300));

        javax.swing.GroupLayout panelSFPaintLayout = new javax.swing.GroupLayout(panelSFPaint);
        panelSFPaint.setLayout(panelSFPaintLayout);
        panelSFPaintLayout.setHorizontalGroup(
            panelSFPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        panelSFPaintLayout.setVerticalGroup(
            panelSFPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSFLayout = new javax.swing.GroupLayout(panelSF);
        panelSF.setLayout(panelSFLayout);
        panelSFLayout.setHorizontalGroup(
            panelSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSFPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSFLayout.setVerticalGroup(
            panelSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSFPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel3D.setBorder(javax.swing.BorderFactory.createTitledBorder("3D Structure"));
        panel3D.setToolTipText("");

        panel3DPaint.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout panel3DPaintLayout = new javax.swing.GroupLayout(panel3DPaint);
        panel3DPaint.setLayout(panel3DPaintLayout);
        panel3DPaintLayout.setHorizontalGroup(
            panel3DPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panel3DPaintLayout.setVerticalGroup(
            panel3DPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel3DLayout = new javax.swing.GroupLayout(panel3D);
        panel3D.setLayout(panel3DLayout);
        panel3DLayout.setHorizontalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel3DPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3DLayout.setVerticalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel3DPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crygetter/gui/icons/accept.png"))); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOk)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel3D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1030, 536));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaObs;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl1V;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl3V;
    private javax.swing.JLabel lblFP;
    private javax.swing.JLabel lblFPV;
    private javax.swing.JLabel lblGroup;
    private javax.swing.JLabel lblGroupV;
    private javax.swing.JLabel lblHI;
    private javax.swing.JLabel lblHIV;
    private javax.swing.JLabel lblMM;
    private javax.swing.JLabel lblMMV;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameV;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblSA;
    private javax.swing.JLabel lblSAV;
    private javax.swing.JLabel lblSCC;
    private javax.swing.JLabel lblSCCV;
    private javax.swing.JLabel lblSCG;
    private javax.swing.JLabel lblSCGV;
    private javax.swing.JLabel lblSCP;
    private javax.swing.JLabel lblSCPV;
    private javax.swing.JLabel lblVDW;
    private javax.swing.JLabel lblVDWV;
    private javax.swing.JPanel panel3D;
    private javax.swing.JPanel panel3DPaint;
    private javax.swing.JPanel panelDetails;
    private javax.swing.JPanel panelSF;
    private javax.swing.JPanel panelSFPaint;
    private javax.swing.JScrollPane spObs;
    // End of variables declaration//GEN-END:variables
}
