/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package crygetter.gui;

import crygetter.utils.Utils;
import java.awt.Desktop;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Properties;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author David
 */
public class MViewConfiguration extends javax.swing.JDialog {

    private Properties defaultConfigs;
    private Properties configs;
    
    /**
     * Creates new form MViewConfiguration
     */
    public MViewConfiguration( JDialog parent, boolean modal, Properties defaultConfigs, Properties configs ) {
        
        super( parent, modal );
        initComponents();
        
        this.defaultConfigs = defaultConfigs;
        this.configs = configs;
        
        fieldPP.setText( configs.getProperty( "mwPP" ) );
        comboAC.setSelectedIndex( Integer.parseInt( configs.getProperty( "mwAC" ) ) );
        comboACM.setSelectedIndex( Integer.parseInt( configs.getProperty( "mwACM" ) ) );
        comboAGM.setSelectedIndex( Integer.parseInt( configs.getProperty( "mwAGM" ) ) );
        comboCC.setSelectedIndex( Integer.parseInt( configs.getProperty( "mwCC" ) ) );
        comboCCM.setSelectedIndex( Integer.parseInt( configs.getProperty( "mwCCM" ) ) );
        comboCGM.setSelectedIndex( Integer.parseInt( configs.getProperty( "mwCGM" ) ) );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        panelOpt = new javax.swing.JPanel();
        lblPP = new javax.swing.JLabel();
        fieldPP = new javax.swing.JTextField();
        btnPP = new javax.swing.JButton();
        btnPPHelp = new javax.swing.JButton();
        lblAC = new javax.swing.JLabel();
        comboAC = new javax.swing.JComboBox();
        lblACM = new javax.swing.JLabel();
        comboACM = new javax.swing.JComboBox();
        lblAGM = new javax.swing.JLabel();
        comboAGM = new javax.swing.JComboBox();
        lblCC = new javax.swing.JLabel();
        comboCC = new javax.swing.JComboBox();
        lblCCM = new javax.swing.JLabel();
        comboCCM = new javax.swing.JComboBox();
        lblCGM = new javax.swing.JLabel();
        comboCGM = new javax.swing.JComboBox();
        btnDefault = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MView Configuration");
        setResizable(false);

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crygetter/gui/icons/accept.png"))); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crygetter/gui/icons/delete.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        panelOpt.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        lblPP.setText("Perl Path:");

        fieldPP.setEditable(false);
        fieldPP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnPP.setText("...");
        btnPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPPActionPerformed(evt);
            }
        });

        btnPPHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crygetter/gui/icons/help.png"))); // NOI18N
        btnPPHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPPHelpActionPerformed(evt);
            }
        });

        lblAC.setText("Alignment Coloring:");

        comboAC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "identity", "any", "consensus", "group" }));
        comboAC.setSelectedIndex(2);

        lblACM.setText("Alignment Color Map:");

        comboACM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "CCLUSTAL", "CLUSTAL", "CHARGE", "CYS", "GPCR", "HXLIN", "NARDI", "P1", "PC1", "POLAR1" }));

        lblAGM.setText("Alignment Group Map:");

        comboAGM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "CYS", "P1" }));

        lblCC.setText("Consensus Coloring:");

        comboCC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "identity", "any" }));
        comboCC.setSelectedIndex(2);

        lblCCM.setText("Consensus Color Map:");

        comboCCM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "CCLUSTAL", "CLUSTAL", "CHARGE", "CYS", "GPCR", "HXLIN", "NARDI", "P1", "PC1", "POLAR1" }));

        lblCGM.setText("Consensus Group Map:");

        comboCGM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "CYS", "P1" }));

        btnDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crygetter/gui/icons/report.png"))); // NOI18N
        btnDefault.setText("Default");
        btnDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefaultActionPerformed(evt);
            }
        });

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crygetter/gui/icons/help.png"))); // NOI18N
        btnHelp.setText("Help EMBL-EBI");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOptLayout = new javax.swing.GroupLayout(panelOpt);
        panelOpt.setLayout(panelOptLayout);
        panelOptLayout.setHorizontalGroup(
            panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblACM, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAGM, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCCM, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCGM, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOptLayout.createSequentialGroup()
                        .addComponent(fieldPP, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPPHelp))
                    .addComponent(comboAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboACM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOptLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDefault)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHelp)
                .addContainerGap())
        );
        panelOptLayout.setVerticalGroup(
            panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPP)
                    .addComponent(fieldPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPP)
                    .addComponent(btnPPHelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAC)
                    .addComponent(comboAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblACM)
                    .addComponent(comboACM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAGM)
                    .addComponent(comboAGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCC)
                    .addComponent(comboCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCCM)
                    .addComponent(comboCCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCGM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHelp)
                    .addComponent(btnDefault))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addComponent(panelOpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(653, 384));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed

        if ( Desktop.isDesktopSupported() ) {
            try {
                Desktop.getDesktop().browse( new URI( "http://www.ebi.ac.uk/Tools/msa/mview/help/" ) );
            } catch ( IOException | URISyntaxException exc ) {
                Utils.showExceptionMessage( this, exc );
            }
        }

    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefaultActionPerformed

        fieldPP.setText( defaultConfigs.getProperty( "mwPP" ) );
        comboAC.setSelectedIndex( Integer.parseInt( defaultConfigs.getProperty( "mwAC" ) ) );
        comboACM.setSelectedIndex( Integer.parseInt( defaultConfigs.getProperty( "mwACM" ) ) );
        comboAGM.setSelectedIndex( Integer.parseInt( defaultConfigs.getProperty( "mwAGM" ) ) );
        comboCC.setSelectedIndex( Integer.parseInt( defaultConfigs.getProperty( "mwCC" ) ) );
        comboCCM.setSelectedIndex( Integer.parseInt( defaultConfigs.getProperty( "mwCCM" ) ) );
        comboCGM.setSelectedIndex( Integer.parseInt( defaultConfigs.getProperty( "mwCGM" ) ) );

    }//GEN-LAST:event_btnDefaultActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        
        configs.setProperty( "mwPP", fieldPP.getText() );
        configs.setProperty( "mwAC", String.valueOf( comboAC.getSelectedIndex() ) );
        configs.setProperty( "mwACM", String.valueOf( comboACM.getSelectedIndex() ) );
        configs.setProperty( "mwAGM", String.valueOf( comboAGM.getSelectedIndex() ) );
        configs.setProperty( "mwCC", String.valueOf( comboCC.getSelectedIndex() ) );
        configs.setProperty( "mwCCM", String.valueOf( comboCCM.getSelectedIndex() ) );
        configs.setProperty( "mwCGM", String.valueOf( comboCGM.getSelectedIndex() ) );
        
        try {
            configs.store( new FileOutputStream( "conf/conf.properties" ), "CryGetter Configuration File - Must not be changed!!!" );
            dispose();
        } catch ( IOException ex ) {
            Utils.showExceptionMessage( this, ex );
        }
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPPActionPerformed
        
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter( 
                "Perl executable (*.exe)", "exe" );

        for ( FileFilter f : jfc.getChoosableFileFilters() ) {
            jfc.removeChoosableFileFilter( f );
        }

        jfc.setFileFilter( fnef );
        jfc.setDialogTitle( "Define Perl Runtime Executable" );
        jfc.setFileSelectionMode( JFileChooser.FILES_ONLY );
        jfc.setMultiSelectionEnabled( false );
        
        if ( jfc.showOpenDialog( this ) == JFileChooser.APPROVE_OPTION ) {
            fieldPP.setText( jfc.getSelectedFile().getAbsolutePath().replace( "\\", "/" ) );
        }
        
    }//GEN-LAST:event_btnPPActionPerformed

    private void btnPPHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPPHelpActionPerformed
        
        JOptionPane.showMessageDialog( this,
                  "MView uses Perl to execute. So, if you want to use it\n"
                + "as an aligment view tool, you will need to define a\n"
                + "local perl runtime (perl executable).", 
                "Information", JOptionPane.INFORMATION_MESSAGE );
        
    }//GEN-LAST:event_btnPPHelpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDefault;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPP;
    private javax.swing.JButton btnPPHelp;
    private javax.swing.JComboBox comboAC;
    private javax.swing.JComboBox comboACM;
    private javax.swing.JComboBox comboAGM;
    private javax.swing.JComboBox comboCC;
    private javax.swing.JComboBox comboCCM;
    private javax.swing.JComboBox comboCGM;
    private javax.swing.JTextField fieldPP;
    private javax.swing.JLabel lblAC;
    private javax.swing.JLabel lblACM;
    private javax.swing.JLabel lblAGM;
    private javax.swing.JLabel lblCC;
    private javax.swing.JLabel lblCCM;
    private javax.swing.JLabel lblCGM;
    private javax.swing.JLabel lblPP;
    private javax.swing.JPanel panelOpt;
    // End of variables declaration//GEN-END:variables
}
